# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build test

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: test branch
        run: echo "branch - ${{ env.GITHUB_REF_SLUG }}"
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install chome
        run: |
          sudo apt-get update
          sudo apt-get install -y libappindicator1 fonts-liberation
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome*.deb
      - name: npm install
        run: |
          npm ci
      - name: Build
        run: |
          npm run render:WithFetch
        env:
          accessKeyId: ${{ secrets.accessKeyId }}
          secretAccessKey: ${{ secrets.secretAccessKey }}
          client_id: ${{ secrets.client_id }}
          client_secret: ${{ secrets.client_secret }}
          password: ${{ secrets.password }}
          LegacyKey: ${{ secrets.LegacyKey }}
          PageCount: 100
          branch: test
          FetchAllData: false
          AlsoWriteLocalJSONFiles: true
          bucket: gard-rarediseases-json
          LogFileSave: false
          FetchThreads: 20
      - name: Compress
        run: |
          mkdir dist/zip
          tar -zcvf dist/zip/deploy-test.tar.gz dist/static
      - name: Upload to S3
        # You may pin to the exact commit or the version.
        # uses: shallwefootball/upload-s3-action@bcd7c2408245fd6cd19b5512a473b1a7a8b48a35
        uses: shallwefootball/upload-s3-action@v1.1.3
        with:
          # aws key id
          aws_key_id: ${{ secrets.accessKeyId }}
          # aws secret access key
          aws_secret_access_key: ${{ secrets.secretAccessKey }}
          # aws bucket name
          aws_bucket: gard-rarediseases-json
          # directory to upload
          source_dir: dist/zip
          # destination directory for upload
          destination_dir: build
      - name: Call Webhook
        run: curl -X POST -d {} "https://webhooks.amplify.us-east-2.amazonaws.com/prod/webhooks?id=${{ secrets.AmplifyId_test }}&token=${{ secrets.AmplifyToken_test }}&operation=startbuild" -H "Content-Type:application/json"
